export const ROLES = {
    TEAM_LEADER: "TEAM_LEADER",
    TEAM_MEMBER: "TEAM_MEMBER",
    ADMIN: "ADMIN",
};
export const PAYMENT_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED",
};
export const REGISTRATION_STATUS = {
    PENDING_PAYMENT: "PENDING_PAYMENT",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
};
export const PROBLEM_STATUS = {
    AVAILABLE: "AVAILABLE",
    FULL: "FULL",
    LOCKED: "LOCKED",
    INACTIVE: "INACTIVE",
};
export const SELECTION_STATUS = {
    SELECTED: "SELECTED",
    RESET: "RESET",
    REASSIGNED: "REASSIGNED",
    ADMIN_OVERRIDE: "ADMIN_OVERRIDE",
};
